@startuml Sequence Diagram
actor User
User -> ChargingStation: Scooter Request
ChargingStation -> Scooter: Checks available charged scooters
ChargingStation <-- Scooter: Returns first available scooter id
User <- ChargingStation: Requests payment
User --> ChargingStation: Returns payment
User <- ChargingStation: Allows use of scooter
User -> ChargingStation: Returns scooter
ChargingStation -> Scooter: Charges battery
ChargingStation <-- Scooter: Battery is charged
@enduml